/**
 * Build Helper Script
 * 
 * This script ensures necessary files exist before building the application.
 * It's designed to be run by Netlify during the build process.
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

// Get current directory
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, '../..');  // Go up to project root

// Files to check/create
const ENV_FILE = path.join(rootDir, '.env');
const ENV_EXAMPLE_FILE = path.join(rootDir, '.env.example');

console.log('🔄 Running build helper script...');

// Ensure .env file exists (copy from .env.example if needed)
if (!fs.existsSync(ENV_FILE)) {
  console.log('ℹ️ No .env file found, creating one from .env.example');
  
  // Check if .env.example exists
  if (fs.existsSync(ENV_EXAMPLE_FILE)) {
    // Copy .env.example to .env
    fs.copyFileSync(ENV_EXAMPLE_FILE, ENV_FILE);
    console.log('✅ Created .env file from .env.example');
  } else {
    // Create minimal .env file
    const minimalEnv = `# Generated by build-helper.js
VITE_HUGGINGFACE_API_TOKEN=your_huggingface_api_token_here
HUGGINGFACE_API_TOKEN=your_huggingface_api_token_here
VITE_HF_API_URL=https://api-inference.huggingface.co/models/stabilityai/stable-diffusion-2-1
HF_API_URL=https://api-inference.huggingface.co/models/stabilityai/stable-diffusion-2-1
VITE_ENABLE_DIRECT_API=true
VITE_ENABLE_CORS_PROXY=true
`;
    fs.writeFileSync(ENV_FILE, minimalEnv);
    console.log('✅ Created minimal .env file');
  }
} else {
  console.log('✅ .env file already exists');
}

console.log('✅ Build preparation complete!'); 